services:

  app:
    image: "registry.gitlab.com/fun-tech/fundraising-frontend-docker:latest"
    volumes:
      - ./matomo:/var/www/html
      - ../CampaignVisitorsByTime:/var/www/html/plugins/CampaignVisitorsByTime
    working_dir: /var/www/html

  cron:
    image: "registry.gitlab.com/fun-tech/fundraising-frontend-docker:latest"
    volumes_from:
      - app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep ${CRON_RUNTIME_SECONDS}
      done
      EOF'

  web:
    image: nginx
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static_test.html:/var/www/html/static_test.html
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST

  db:
    image: mariadb:10.6
    volumes:
      - db-storage:/var/lib/mysql
      # If you have a database dump, put it here
      - ./mysql/data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD


volumes:
  db-storage:
